buddy_baer_frontend:
    resource: "@BuddyBaerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

buddy_baer_manager:
    resource: "@BuddyBaerManagerBundle/Resources/config/routing.yml"
    prefix:   /

